<?php include($_SERVER['DOCUMENT_ROOT']."/the-tower-at-opop/live-site/template/header.inc.php"); ?>
<section class="general">
	<div class="content">
	    <h1>The Tower Terms &amp; Conditions</h1>
	    <p>This page states the Terms and Conditions under which you, the Web Site visitor, may use www.TheTowerAtOPOP.com (the "Site"), which is owned by North American Properties (NAP).</p>
	    <p>Please read this page carefully. By using this Site, you agree to be bound by all of the Terms and Conditions set forth below. If you do not accept these Terms and Conditions, please do not use this Site. NAP may, in its sole discretion, revise these Terms and Conditions at any time; therefore, you should visit this page periodically to review the Terms and Conditions.</p>
	    <h4>Use of Site Material</h4>
	    <p>The contents of this Site, such as text, graphics, images and other content (the "Site Material") are protected by copyright under both United States and foreign laws. These Terms and Conditions do not grant you any license whatsoever to the Site Material except as described in this paragraph. NAP authorizes you to view and download a single copy of the Site Material for your non-commercial personal use. Unauthorized use of the Site Material violates copyright, trademark, and other laws. You agree to retain all copyright and other proprietary notices contained in the original Site Material or any copy of such material. Except as expressly provided herein, you may not sell or modify our Site Material or reproduce, display, distribute, or otherwise use the Site Material in any way for any public or commercial purpose. Use of the Site Material on any other Web Site or in a networked environment is prohibited. NAP retains all intellectual property rights in the Site Material.</p>
	    <h4>Trademarks</h4>
	    <p>The names, marks and logos appearing on the Site are, unless otherwise noted, trademarks owned by or licensed to NAP. Your use of these marks, except as provided in these Terms and Conditions, is prohibited. From time to time, NAP makes fair use in this Site of trademarks owned and used by third parties. NAP makes no claim to ownership of those marks.</p>
	    <h4>User Submissions</h4>
	    <p>NAP welcomes your comments on our Site. However, you acknowledge that if you send us creative suggestions, ideas, notes, drawings, concepts, inventions or other information, (collectively, the "Information"), the Information shall be deemed, and shall remain NAP property. By submission of any Information to us, you assign to us and we shall own exclusively all rights to such Information of every kind and nature throughout the universe now known or hereafter existing. NAP shall be entitled to unrestricted use of the Information for any purpose whatsoever, commercial or otherwise, without compensation to you or the provider of the information.</p>
	    <p>As a user of this Web Site, you are responsible for your own communications. Therefore, do not do any of the following things:</p>
		<ul>
			<li>transmit to us material that is copyrighted, unless you are the copyright owner or have the permission of the copyright owner;</li>
			<li>send material that reveals trade secrets, unless you own them or have the permission of the owner;</li>
	    	<li>send material that infringes on any other intellectual property rights of others or on the privacy or publicity rights of others;</li>
	    	<li>send material that is obscene, defamatory, threatening, harassing, abusive, hateful, or embarrassing to another user or any other person or entity;</li>
	    	<li>intentionally or unintentionally violate or encourage conduct that would violate any local, state, or federal law;</li>
	    	<li>send advertisements or solicitations of business;</li>
	    	<li>send chain letters or pyramid schemes; or</li>
	    	<li>impersonate another person.</li>
		</ul>
	    <p>NAP reserves the right to expel you and to prevent you further access to this Site for violating these Terms and Conditions terms or the law. The violation of any of these Terms and Conditions shall result in the immediate revocation of your right to access or use the Site or Site Material and obligates you to immediately destroy any copies of the Site Material in your possession.</p>
	    <h4>Limitation of Liability</h4>
	    <p>NAP DOES NOT WARRANT THAT THIS WEB SITE WILL OPERATE ERROR-FREE OR THAT THE SITE AND ITS SERVER ARE FREE OF COMPUTER VIRUSES OR OTHER HARMFUL MATERIAL. IF YOUR USE OF THIS SITE OR THIS SITE MATERIAL RESULTS IN ANY COSTS OR EXPENSES, INCLUDING, WITHOUT LIMITATION, THE NEED FOR SERVICING OR REPLACING EQUIPMENT OR DATA, NAP SHALL NOT BE RESPONSIBLE FOR THOSE COSTS OR EXPENSES.</p>
	    <p>THIS WEB SITE AND ITS MATERIAL ARE PROVIDED ON AN "AS IS" AND "AT YOUR OWN RISK" BASIS WITHOUT ANY WARRANTIES OF ANY KIND. NAP, TO THE FULLEST EXTENT PERMITTED BY LAW, DISCLAIMS ALL WARRANTIES, INCLUDING THE WARRANTY OF MERCHANTABILITY, NON-INFRINGEMENT OF THIRD PARTIES RIGHTS, AND THE WARRANTY OF FITNESS FOR PARTICULAR PURPOSE. ALTHOUGH NAP STRIVES TO PROVIDE THOROUGH AND ACCURATE MATERIALS ON ITS SITE, WE MAKE NO WARRANTIES ABOUT THE ACCURACY, RELIABILITY, COMPLETENESS, OR TIMELINESS OF THE MATERIAL, SERVICES, SOFTWARE, TEXT, GRAPHICS, AND LINKS.</p>
	    <p>NAP DOES NOT MAKE ANY WARRANTIES AS TO THE RESULT OR OUTCOME OF USING THE SITE OR PROPERLY FOLLOWING ANY INSTRUCTIONS, RECOMMENDATIONS, DIRECTIONS, OR RECIPES CONTAINED IN THE SITE MATERIAL.</p>
	    <h4>Disclaimer of Consequential Damages</h4>
	    <p>IN NO EVENT SHALL NAP, ITS AFFILIATES, OR ANY THIRD PARTIES MENTIONED ON THE SITE BE LIABLE FOR ANY DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, INCIDENTAL, INDIRECT, CONSEQUENTIAL OR PUNITIVE DAMAGES, LOST PROFITS, OR DAMAGES RESULTING FROM LOST DATA OR BUSINESS INTERRUPTION) RESULTING FROM THE USE OR INABILITY TO USE MATERIAL ON THIS SITE OR SITES LINKED TO THIS SITE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT NAP IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
	    <h4>Links</h4>
	    <p>This Site may contain links to Web Sites owned by third parties. These links are provided solely as a convenience to you and are not an endorsement by NAP of the contents on those other sites. NAP is not responsible for the content of any linked sites and makes no representations regarding the content or accuracy of materials on such sites. If you decide to visit any third-party sites using links from this Site, you do so at your own risk. Consult the Uniform Resources Locator ("URL") address identified in your browser to determine whether you have linked to a third-party Site.</p>
	    <h4>Indemnity</h4>
	    <p>By using this Site, you agree to defend, indemnify, and hold harmless NAP, its officers, directors, employees and agents, from and against any and all losses, claims, damages, costs and expenses (including reasonable legal and accounting fees) that NAP may become obligated to pay arising or resulting from your use of the Site Material or your breach of these Terms and Conditions. NAP reserves the right to assume or participate, at your expense, in the investigation, settlement and defense of any such action or claim.</p>
	    <h4>Privacy</h4>
	    <p>Please see NAP's Privacy Policy, <a href="<?php echo MAINURL; ?>privacy-policy" title="Privacy Policy">located here</a>.</p>
	    <h4>Miscellaneous</h4>
	    <p>This Web Site originates from Frisco, TX. NAP does not claim that the Site Material is appropriate or may be used outside of the United States. Access to the Site Material may not be legal by certain persons or in certain countries. If you access the Site from outside of the United States, you do so at your own risk and are responsible for compliance with the laws of your jurisdiction.</p>
	    <p>These Terms and Conditions are governed by the substantive laws of the State of Texas, without respect to its conflict of laws principles. You agree to submit to the jurisdiction of the courts situated in the State of Texas with respect to any dispute, disagreement, or cause of action related to or involving this Site. If any provision is found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms and Conditions, which shall remain in full force and effect. No waiver of any of these Terms and Conditions shall be deemed a further or continuing waiver of such term or any other term. Except as expressly provided elsewhere in our Site, these Terms and Conditions constitute the entire agreement between you and NAP with respect to your use of this Site.</p>
	</div>
</section>

<?php include($_SERVER['DOCUMENT_ROOT']."/the-tower-at-opop/live-site/template/footer.inc.php"); ?>        